services:
  - type: web
    name: myprof-educ-api
    runtime: node
    repo: https://github.com/MyPof/myprof-backend
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
